name: cuaderno1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+2
  flutter_svg: ^2.0.5
  provider: ^6.1.5+1
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  audioplayers: ^5.2.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.1
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/youtube.svg
    - assets/images/google.svg
    - assets/images/language.svg
    - assets/audio/ring.mp3